import {useEffect,useState} from 'react';
import {Plus,Check,Clock,CheckCheck,ArrowLeft,ArrowRight,Search,UserPlus,CalendarDays,Phone,RefreshCw,CheckCircle2,X,Pencil} from 'lucide-react';
import {type Ctx,type Row,api,useApi,query,today,monthNow,dateBR,timeBR,cpf,phone,Avatar,Status,Modal,Confirm,ErrorBox,Loading,Empty,SearchBox,Field,Calendar} from './lib';
import {RegistryForm,ClientDetail} from './Registry';
export default function Agenda({ctx}:{ctx:Ctx}){
 const[date,setDate]=useState(today()),[specialty,setSpecialty]=useState(''),[search,setSearch]=useState(''),[finished,setFinished]=useState(false),[detail,setDetail]=useState<number|null>(null),[action,setAction]=useState<Row|null>(null);
 const{data:rows,loading,error,reload}=useApi('/appointments?'+query({date,...(specialty?{specialty_id:specialty}:{})}));
 useEffect(()=>{const t=setInterval(reload,15000);return()=>clearInterval(t)},[date,specialty]);
 const filtered=(rows||[]).filter((a:Row)=>(a.client.name+' '+a.client.cpf).toLowerCase().includes(search.toLowerCase())),scheduled=filtered.filter((a:Row)=>a.status==='scheduled'),waiting=filtered.filter((a:Row)=>a.status==='confirmed'),completed=(rows||[]).filter((a:Row)=>a.status==='completed');
 const [busy,setBusy]=useState<number|null>(null),[actionError,setActionError]=useState('');
 async function transition(a:Row,status:string){setBusy(a.id);setActionError('');try{await api('/appointments/'+a.id+'/status','PATCH',{status});reload();ctx.notify(status==='confirmed'?'Presença confirmada. Cliente entrou na fila.':'Atendimento finalizado.')}catch(e){setActionError((e as Error).message);reload()}finally{setBusy(null)}}
 const card=(a:Row,index:number,queue=false)=><div className={'appointment-card '+(queue?'in-queue':'')} key={a.id}><div className="appointment-top">{queue&&<span className="queue-number">{String(index+1).padStart(2,'0')}</span>}<Avatar name={a.client.name}/><div className="grow"><button className="name-button" onClick={()=>setDetail(a.client.id)}>{a.client.name}</button><span className="contact"><Phone size={13}/>{phone(a.client.phone)}</span></div>{!queue&&<button className="icon-button" aria-label="Opções da consulta" onClick={()=>setAction(a)}><Pencil size={16}/></button>}</div><div className="appointment-meta"><span className="specialty-pill">{a.slot.specialty.name}</span><span>{a.slot.doctor.name}</span></div><div className="appointment-footer"><small>{queue?<><Clock size={14}/> Chegou às {timeBR(a.confirmed_at)}</>:<>Consulta #{String(a.id).padStart(4,'0')}</>}</small><button className={'button compact '+(queue?'success':'soft')} disabled={busy===a.id||date!==today()} onClick={()=>queue?setAction({...a,complete:true}):transition(a,'confirmed')}>{queue?<CheckCheck size={16}/>:<Check size={16}/>}{busy===a.id?'Salvando…':queue?'Finalizar atendimento':'Confirmar presença'}</button></div></div>;
 return <><div className="page-heading"><div><div className="eyebrow">RECEPÇÃO</div><h1>Agendamentos</h1><p>Da chegada ao atendimento, todo o cuidado em um só lugar.</p></div><button className="button" onClick={()=>ctx.navigate('booking')}><Plus size={18}/>Novo agendamento</button></div><div className="agenda-toolbar"><label className="date-control"><CalendarDays size={18}/><input aria-label="Dia dos atendimentos" type="date" value={date} onChange={e=>{if(e.target.value)setDate(e.target.value)}}/></label><select aria-label="Filtrar especialidade" value={specialty} onChange={e=>setSpecialty(e.target.value)}><option value="">Todas as especialidades</option>{ctx.options.specialties?.map((s:Row)=><option key={s.id} value={s.id}>{s.name}</option>)}</select><SearchBox value={search} onChange={setSearch}/><button className="button secondary" onClick={()=>setFinished(true)}><CheckCheck size={17}/>Finalizados <span className="count">{completed.length}</span></button><button className="icon-button" onClick={reload} aria-label="Atualizar fila"><RefreshCw size={18}/></button></div><ErrorBox message={error||actionError}/>{date!==today()&&<div className="notice">Você está consultando a agenda de {dateBR(date)}. A presença e a finalização são registradas no dia do atendimento.</div>}
 {loading&&!rows?<Loading/>:<div className="queue-grid"><section className="queue-column"><div className="queue-heading"><div><span className="mini-icon blue"><CalendarDays size={19}/></span><h2>Agendados <span>{scheduled.length}</span></h2></div><small>Aguardando chegada</small></div>{scheduled.length?scheduled.map((a:Row,i:number)=>card(a,i)):<Empty title="Tudo em dia por aqui" text="Nenhum cliente aguardando confirmação nesta seleção."/>}</section><section className="queue-column confirmed-column"><div className="queue-heading"><div><span className="mini-icon teal"><Clock size={19}/></span><h2>Fila de atendimento <span>{waiting.length}</span></h2></div><small>Por ordem de chegada</small></div>{waiting.length?waiting.map((a:Row,i:number)=>card(a,i,true)):<Empty title="Aguardando a primeira chegada" text="Confirme a presença de um cliente para adicioná-lo à fila."/>}</section></div>}
 {finished&&<Modal wide title={'Atendimentos finalizados · '+dateBR(date)} onClose={()=>setFinished(false)}>{completed.length?<div className="table-scroll"><table><thead><tr><th>Cliente</th><th>Especialidade</th><th>Finalizado às</th></tr></thead><tbody>{completed.map((a:Row)=><tr key={a.id}><td>{a.client.name}</td><td>{a.slot.specialty.name}</td><td>{timeBR(a.completed_at)}</td></tr>)}</tbody></table></div>:<Empty title="Nenhum atendimento finalizado"/>}</Modal>}
 {detail&&<ClientDetail id={detail} ctx={ctx} onClose={()=>setDetail(null)}/>}
 {action&&(action.complete?<Confirm title="Finalizar atendimento" text={`Confirmar o atendimento de ${action.client.name} em ${action.slot.specialty.name}? O cliente sairá da fila.`} label="Finalizar atendimento" onClose={()=>setAction(null)} onConfirm={async()=>{await api('/appointments/'+action.id+'/status','PATCH',{status:'completed'});reload();ctx.notify('Atendimento finalizado.')}}/>:<Modal title="Gerenciar consulta" onClose={()=>setAction(null)}><h3>{action.client.name}</h3><p>{dateBR(action.slot.date)} · {action.slot.specialty.name}</p><div className="form-actions"><button className="button secondary" onClick={()=>ctx.navigate('booking/'+action.id+'/'+action.client.id)}>Remarcar</button><button className="button danger" onClick={()=>setAction({...action,cancel:true})}>Cancelar consulta</button></div>{action.cancel&&<Confirm title="Cancelar consulta" text="A consulta será cancelada e a vaga ficará disponível para outra pessoa." label="Cancelar consulta" danger onClose={()=>setAction(null)} onConfirm={async()=>{await api('/appointments/'+action.id+'/status','PATCH',{status:'cancelled'});reload();ctx.notify('Consulta cancelada.')}}/>}</Modal>)}
 </>
}
export function Booking({ctx,appointmentId,clientId}:{ctx:Ctx;appointmentId?:number;clientId?:number}){
 const[client,setClient]=useState<Row|null>(null),[searchCpf,setSearchCpf]=useState(''),[newClient,setNewClient]=useState(false),[lookupBusy,setLookupBusy]=useState(false),[lookupError,setLookupError]=useState('');
 const[month,setMonth]=useState(monthNow()),[specialty,setSpecialty]=useState(''),[day,setDay]=useState(''),[slot,setSlot]=useState<Row|null>(null),[confirm,setConfirm]=useState(false);
 useEffect(()=>{if(clientId)api('/clients/'+clientId).then(setClient).catch(e=>setLookupError(e.message))},[clientId]);
 const{data:slots,loading,error,reload}=useApi(specialty?'/slots?'+query({month,specialty_id:specialty}):null);
 async function lookup(){setLookupBusy(true);setLookupError('');setClient(null);try{const result=await api('/clients/lookup?cpf='+encodeURIComponent(searchCpf));if(result.client){setClient(result.client);ctx.notify('Cadastro encontrado.')}else setNewClient(true)}catch(e){setLookupError((e as Error).message)}finally{setLookupBusy(false)}}
 const daySlots=(slots||[]).filter((s:Row)=>s.date===day&&s.status==='available');
 return <><button className="back-link" onClick={()=>ctx.navigate('agenda')}><ArrowLeft size={17}/>Voltar para agendamentos</button><div className="page-heading"><div><div className="eyebrow">{appointmentId?'REMARCAÇÃO':'NOVO ATENDIMENTO'}</div><h1>{appointmentId?'Remarcar consulta':'Agendar um cuidado'}</h1><p>Localize o cliente e escolha uma vaga disponível.</p></div></div><div className="booking-grid"><section className="panel booking-calendar"><div className="panel-head"><div><h2><span className="step">2</span> Escolha o atendimento</h2><p>Encontre uma data na especialidade desejada</p></div></div><div className="panel-body"><Field label="Especialidade médica"><select value={specialty} onChange={e=>{setSpecialty(e.target.value);setDay('');setSlot(null)}}><option value="">Selecione uma especialidade</option>{ctx.options.specialties?.map((s:Row)=><option key={s.id} value={s.id}>{s.name}</option>)}</select></Field>{specialty?<><ErrorBox message={error}/>{loading?<Loading/>:<Calendar month={month} onMonth={s=>{setMonth(s);setDay('');setSlot(null)}} slots={slots||[]} selected={day?[day]:[]} onSelect={d=>{setDay(d);setSlot(null)}}/>}{day&&<div className="day-slots"><h3>Vagas em {dateBR(day)}</h3>{daySlots.length?daySlots.map((s:Row)=><button className={'slot-choice '+(slot?.id===s.id?'chosen':'')} key={s.id} disabled={s.booked>=s.capacity} onClick={()=>setSlot(s)}><div><strong>{s.doctor.name}</strong><small>{s.specialty.name}</small></div><span>{s.capacity-s.booked} vagas</span>{slot?.id===s.id&&<CheckCircle2 size={19}/>}</button>):<Empty title="Nenhuma oferta neste dia" text="Escolha um dia verde no calendário."/>}</div>}</>:<Empty title="Qual especialidade o cliente precisa?" text="Selecione uma especialidade para consultar as vagas."/>}</div></section>
 <div className="booking-client"><section className="panel"><div className="panel-head"><div><h2><span className="step">1</span> Identifique o cliente</h2><p>Busque pelo CPF antes de cadastrar</p></div></div><div className="panel-body"><form onSubmit={e=>{e.preventDefault();lookup()}}><Field label="CPF do cliente"><div className="input-action"><input value={searchCpf} onChange={e=>setSearchCpf(e.target.value)} placeholder="000.000.000-00" inputMode="numeric" required maxLength={14}/><button className="button" disabled={lookupBusy}>{lookupBusy?'…':<Search size={19}/>}<span>Buscar</span></button></div></Field></form><ErrorBox message={lookupError}/>{client?<div className="selected-client"><span className="badge completed"><Check size={13}/>Cadastro localizado</span><div className="person"><Avatar name={client.name} src={client.photo_url}/><div><h3>{client.name}</h3><small>{cpf(client.cpf)}</small></div></div><p><Phone size={15}/>{phone(client.phone)}</p><p>Nascimento: {dateBR(client.birth_date)}</p><p>{client.neighborhood||'Bairro não informado'}</p><button className="text-button" onClick={()=>{setClient(null);setSearchCpf('')}}>Trocar cliente</button></div>:<div className="lookup-note"><UserPlus size={24}/><p>Se o CPF ainda não estiver cadastrado, você poderá cadastrar o cliente aqui.</p></div>}</div></section><section className="booking-summary"><h3>Resumo do agendamento</h3><div><small>Cliente</small><strong>{client?.name||'Selecione o cliente'}</strong></div><div><small>Atendimento</small><strong>{slot?slot.specialty.name+' · '+dateBR(slot.date):'Selecione uma vaga'}</strong>{slot&&<span>{slot.doctor.name}</span>}</div><button className="button full" disabled={!client||!slot} onClick={()=>setConfirm(true)}>{appointmentId?'Confirmar remarcação':'Confirmar agendamento'}<ArrowRight size={18}/></button><p>Atendimento gratuito à comunidade</p></section></div></div>
 {newClient&&<Modal wide title="CPF não cadastrado · Novo cliente" onClose={()=>setNewClient(false)}><RegistryForm entity="clients" initial={{cpf:searchCpf.replace(/\D/g,'')}} ctx={ctx} onClose={()=>setNewClient(false)} onSaved={c=>{setClient(c);setNewClient(false);ctx.notify('Cliente cadastrado. Agora escolha a vaga.')}}/></Modal>}
 {confirm&&client&&slot&&<Confirm title={appointmentId?'Confirmar remarcação':'Confirmar agendamento'} text={`${client.name} · ${slot.specialty.name} com ${slot.doctor.name}, em ${dateBR(slot.date)}.`} label="Confirmar" onClose={()=>setConfirm(false)} onConfirm={async()=>{try{await api('/appointments'+(appointmentId?'/'+appointmentId:''),appointmentId?'PUT':'POST',{client_id:client.id,slot_id:slot.id});ctx.notify('Consulta agendada com sucesso.');ctx.navigate('agenda')}catch(e){reload();throw e}}}/>}
 </>
}
