import {useState} from 'react';
import {ArrowUpRight,ArrowRight,Users,UserPlus,HeartPulse,CalendarCheck,Plus,Clock,CheckCheck,Sparkles} from 'lucide-react';
import {type Ctx,useApi,monthNow,number,Loading,ErrorBox,Avatar,Status,dateBR,Empty} from './lib';
export default function Dashboard({ctx}:{ctx:Ctx}){
 const[month,setMonth]=useState(monthNow()),{data:d,loading,error}=useApi('/dashboard?month='+month);
 if(loading)return <Loading/>;if(error)return <ErrorBox message={error}/>;
 const stats=[['Atendimentos no mês',d.stats.month_appointments,HeartPulse,'blue'],['Novos clientes no mês',d.stats.new_clients,UserPlus,'teal'],['Clientes cadastrados',d.stats.total_clients,Users,'purple'],['Atendimentos realizados',d.stats.total_appointments,CalendarCheck,'green']] as const;
 const days=new Date(Number(month.slice(0,4)),Number(month.slice(5)),0).getDate(),values=Array.from({length:days},(_,i)=>Number(d.series.find((r:any)=>r.date===month+'-'+String(i+1).padStart(2,'0'))?.count||0)),max=Math.max(5,...values);
 return <><div className="page-heading"><div><div className="eyebrow">VISÃO GERAL</div><h1>Cuidar começa por aqui<span className="heading-dot">.</span></h1><p>Bem-vindo, {ctx.user.name.split(' ')[0]}. Acompanhe o dia da clínica.</p></div><button className="button" onClick={()=>ctx.navigate('booking')}><Plus size={18}/>Novo agendamento</button></div>
 <div className="section-line"><h2>Resumo da clínica</h2><label className="month-control">Período<input type="month" value={month} onChange={e=>{if(e.target.value)setMonth(e.target.value)}}/></label></div>
 <div className="stats-grid">{stats.map(([label,value,Icon,color],i)=><div className="stat-card" key={label}><div className={'stat-icon '+color}><Icon size={21}/></div><span className="stat-label">{label}</span><strong>{number(value)}</strong><small>{i<2?'No período selecionado':'Desde o início da clínica'}<ArrowUpRight size={15}/></small></div>)}</div>
 <div className="dashboard-main"><section className="panel chart-panel"><div className="panel-head"><div><h2>Atendimentos ao longo do mês</h2><p>Consultas finalizadas por dia</p></div><span className="chart-key"><i/>Atendimentos</span></div><div className="chart" role="img" aria-label={`Atendimentos por dia: ${values.map((v,i)=>`dia ${i+1}: ${v}`).join(', ')}`}><div className="chart-y">{[max,Math.round(max*.75),Math.round(max*.5),Math.round(max*.25),0].map((v,i)=><span key={i}>{v}</span>)}</div><div className="bars">{values.map((v,i)=><div className="bar-track" key={i}><div className="bar" style={{height:`${v/max*100}%`,minHeight:v?4:0}} title={`Dia ${i+1}: ${v} atendimentos`}/><span>{i%5===0||i===days-1?String(i+1).padStart(2,'0'):''}</span></div>)}</div></div><div className="chart-caption"><HeartPulse size={16}/>{number(d.stats.month_appointments)} atendimentos gratuitos neste mês</div></section>
 <section className="panel today-panel"><div className="panel-head"><div><h2>Hoje na clínica</h2><p>{new Date().toLocaleDateString('pt-BR',{weekday:'long',day:'numeric',month:'long'})}</p></div><span className="live-dot"/></div><div className="today-row"><span className="mini-icon blue"><CalendarCheck size={20}/></span><div><strong>Agendados</strong><small>Aguardando confirmação</small></div><b>{d.today.scheduled}</b></div><div className="today-row"><span className="mini-icon teal"><Clock size={20}/></span><div><strong>Na fila de atendimento</strong><small>Presença confirmada</small></div><b>{d.today.waiting}</b></div><div className="today-row"><span className="mini-icon green"><CheckCheck size={20}/></span><div><strong>Finalizados</strong><small>Atendimentos concluídos</small></div><b>{d.today.completed}</b></div><button className="button soft full" onClick={()=>ctx.navigate('agenda')}>Abrir fila de atendimento<ArrowRight size={17}/></button></section></div>
 <div className="dashboard-bottom"><section className="panel"><div className="panel-head"><div><h2>Próximos atendimentos de hoje</h2><p>Quem estamos esperando na clínica</p></div><button className="text-button" onClick={()=>ctx.navigate('agenda')}>Ver agenda<ArrowRight size={16}/></button></div>{!d.appointments.length?<Empty title="Agenda em dia" text="Não há consultas aguardando atendimento hoje."/>:<div className="table-scroll"><table><thead><tr><th>Cliente</th><th>Especialidade</th><th>Situação</th></tr></thead><tbody>{d.appointments.map((a:any)=><tr key={a.id}><td><div className="person"><Avatar name={a.client.name}/><div><strong>{a.client.name}</strong><small>{a.slot.doctor.name}</small></div></div></td><td>{a.slot.specialty.name}</td><td><Status value={a.status}/></td></tr>)}</tbody></table></div>}</section>
 <section className="panel"><div className="panel-head"><div><h2>Ocupação por especialidade</h2><p>Agendamentos / vagas oferecidas</p></div></div><div className="occupancy">{d.specialties.map((s:any,i:number)=><div key={s.name}><div className="between"><strong>{s.name}</strong><span>{s.booked} <small>/ {s.capacity}</small></span></div><div className="progress-track"><i style={{width:`${Math.min(100,s.booked/s.capacity*100)}%`,background:i%2?'#14b8a6':'#2563eb'}}/></div></div>)}{!d.specialties.length&&<Empty title="Sem vagas no período"/>}</div></section></div>
 {d.insights.length>0&&<section className="insights"><div className="insight-title"><Sparkles size={20}/><h2>Olhar sobre a operação</h2><span>Baseado na agenda de {dateBR(month+'-01').slice(3)}</span></div><div className="insight-grid">{d.insights.map((s:any)=><div key={s.title}><strong>{s.title}</strong><p>{s.text}</p></div>)}</div></section>}
 </>
}
