import {useState,useEffect,useRef,type FormEvent} from 'react';
import {Plus,Pencil,Trash2,ArrowRight,Camera,MapPin,Printer,Phone,UserRound,FileText} from 'lucide-react';
import {type Ctx,type Row,api,useApi,query,Avatar,cpf,phone,dateBR,Status,Modal,Confirm,Field,ErrorBox,Loading,Empty,Pager,SearchBox} from './lib';
export const clientFields=[['name','Nome completo','text',true],['cpf','CPF','text',true],['mother','Nome da mãe','text'],['rg','RG','text'],['birth_date','Data de nascimento','date',true],['phone','Telefone / WhatsApp','tel',true],['phone2','Telefone alternativo','tel'],['sus','Cartão SUS','text'],['street','Rua / avenida','text'],['number','Número','text'],['neighborhood','Bairro','text'],['city','Cidade','text'],['state','Estado (UF)','text'],['zip','CEP','text'],['marital_status','Estado civil','select'],['profession','Profissão','text'],['leader_id','Liderança','select'],['latitude','Latitude','number'],['longitude','Longitude','number']] as const;
const addressFields=['street','number','neighborhood','city','state','zip'];
const hasLocation=(row:Row)=>row.latitude!=null&&row.latitude!==''&&row.longitude!=null&&row.longitude!=='';
const configs:Row={clients:{title:'Clientes',single:'cliente',desc:'Cada cadastro é o começo de um cuidado.',fields:clientFields},doctors:{title:'Médicos',single:'médico',desc:'Profissionais que fazem o cuidado acontecer.',fields:[['name','Nome completo','text',true],['cpf','CPF','text',true],['crm','CRM / UF','text',true],['phone','Telefone','tel',true]]},leaders:{title:'Lideranças',single:'liderança',desc:'A conexão entre a comunidade e a clínica.',fields:[['name','Nome completo','text',true],['phone','Telefone','tel',true],['neighborhood','Bairro','text',true]]},specialties:{title:'Especialidades médicas',single:'especialidade',desc:'Áreas de atendimento oferecidas pela clínica.',fields:[['name','Nome da especialidade','text',true]]},users:{title:'Administradores e usuários',single:'usuário',desc:'Controle quem pode acessar e gerenciar o sistema.',fields:[['name','Nome completo','text',true],['cpf','CPF','text',true],['password','Senha (mínimo 10 caracteres)','password'],['level','Nível de acesso','select']]}};
export function RegistryForm({entity,initial={},ctx,onSaved,onClose}:{entity:string;initial?:Row;ctx:Ctx;onSaved:(r:Row)=>void;onClose:()=>void}){
 const[v,setV]=useState<Row>({...{active:true,level:'recepcao',whatsapp_opt_in:false},...initial,specialty_ids:initial.specialties?.map((s:Row)=>s.id)||[]}),[busy,setBusy]=useState(false),[error,setError]=useState(''),[photoFile,setPhotoFile]=useState<File|null>(null);
 const[geo,setGeo]=useState(false),[geoError,setGeoError]=useState(''),[geoLabel,setGeoLabel]=useState('');
 const addressVersion=useRef(0);
 useEffect(()=>()=>{addressVersion.current++},[]);
 const update=(k:string,val:any)=>{
  if(entity==='clients'&&addressFields.includes(k)){addressVersion.current++;setGeoError('');setGeoLabel('');setV(p=>({...p,[k]:k==='state'?String(val).toUpperCase():val,latitude:null,longitude:null}));}
  else setV(p=>({...p,[k]:val}));
 };
 async function locate(){
  const version=addressVersion.current;setGeo(true);setGeoError('');setGeoLabel('');
  try{const location=await api('/clients/geocode','POST',Object.fromEntries(addressFields.map(k=>[k,v[k]??''])));if(version!==addressVersion.current)return;setV(p=>({...p,latitude:location.latitude,longitude:location.longitude}));setGeoLabel(location.display_name);}
  catch(e){if(version===addressVersion.current)setGeoError((e as Error).message)}finally{setGeo(false)}
 }

 async function submit(e:FormEvent){e.preventDefault();if(geo||busy)return;setBusy(true);setError('');try{const payload={...v};for(const k of Object.keys(payload))if(payload[k]==='')payload[k]=null;if(entity==='users'&&!payload.password)delete payload.password;const saved=await api('/'+entity+(initial.id?'/'+initial.id:''),initial.id?'PUT':'POST',payload);if(photoFile){const form=new FormData();form.append('photo',photoFile);try{await api('/clients/'+saved.id+'/photo','POST',form)}catch(e){setV(p=>({...p,id:saved.id}));ctx.notify('Cadastro salvo; a foto não foi enviada: '+(e as Error).message);onSaved(saved);return;}}ctx.refresh();onSaved(saved)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <form onSubmit={submit}><ErrorBox message={error}/><div className="form-grid">{configs[entity].fields.filter(([key]:any)=>!['latitude','longitude'].includes(key)).map(([key,label,type,required]:any)=><Field key={key} label={label+(required?' *':'')}>{type==='select'?<select value={v[key]||''} onChange={e=>update(key,e.target.value)} required={key==='level'}><option value="">Selecione</option>{(key==='leader_id'?ctx.options.leaders||[]:key==='level'?[{id:'admin',name:'Administrador — acesso completo'},{id:'recepcao',name:'Recepção — clientes e agenda'},{id:'gestor',name:'Gestor — clientes, agenda e relatórios'}]:['Solteiro(a)','Casado(a)','União estável','Divorciado(a)','Viúvo(a)'].map(s=>({id:s,name:s}))).map((o:Row)=><option key={o.id} value={o.id}>{o.name}</option>)}</select>:<input type={type} value={v[key]??''} onChange={e=>update(key,type==='number'?(e.target.value===''?'':Number(e.target.value)):e.target.value)} required={required||(entity==='users'&&key==='password'&&!initial.id)} minLength={key==='password'?10:undefined} maxLength={key==='state'?2:key==='cpf'?14:undefined} step={type==='number'?'any':undefined} autoComplete={key==='password'?'new-password':'off'}/>}</Field>)}</div>
 {entity==='doctors'&&<fieldset className="checkbox-group"><legend>Especialidades do médico *</legend>{ctx.options.specialties?.map((s:Row)=><label key={s.id}><input type="checkbox" checked={v.specialty_ids.includes(s.id)} onChange={e=>update('specialty_ids',e.target.checked?[...v.specialty_ids,s.id]:v.specialty_ids.filter((id:number)=>id!==s.id))}/>{s.name}</label>)}</fieldset>}
 {entity==='clients'&&<><section className="location-fields" aria-label="Localização no mapa">
  <div className="geo-action"><MapPin size={18}/><span>Localização no mapa</span><button type="button" className="button secondary" disabled={geo||busy} onClick={locate}>{geo?'Gerando localização…':'Gerar localização pelo endereço'}</button></div>
  <p className="muted">Preencha rua, número, bairro, cidade, UF e CEP e clique no botão. As coordenadas são preenchidas automaticamente e usadas nos relatórios por mapa.</p>
  <div className="form-grid">{['latitude','longitude'].map(key=><Field key={key} label={key==='latitude'?'Latitude':'Longitude'}><input value={v[key]??''} readOnly placeholder="Preenchida pelo endereço"/></Field>)}</div>
  <div role="status" aria-live="polite">{geoLabel?<p>Endereço encontrado: {geoLabel}. Salve o cadastro para manter esta localização.</p>:<p>{hasLocation(v)?'Localização registrada.':'Localização ainda não gerada. Você pode salvar o cadastro e localizar depois.'}</p>}</div>
  {hasLocation(v)&&<p><a href={`https://www.openstreetmap.org/?mlat=${v.latitude}&mlon=${v.longitude}#map=18/${v.latitude}/${v.longitude}`} target="_blank" rel="noreferrer">Conferir ponto no mapa</a> · A posição pode ser aproximada.</p>}
  <ErrorBox message={geoError}/><small>Dados de localização: © <a href="https://www.openstreetmap.org/copyright" target="_blank" rel="noreferrer">OpenStreetMap</a>.</small>
 </section><label className="check-label"><input type="checkbox" checked={!!v.whatsapp_opt_in} onChange={e=>update('whatsapp_opt_in',e.target.checked)}/>Cliente autorizou receber mensagens por WhatsApp</label><Field label="Foto do cliente" hint="JPG, PNG ou WebP, até 4 MB."><input type="file" accept="image/jpeg,image/png,image/webp" capture="user" onChange={e=>setPhotoFile(e.target.files?.[0]||null)}/></Field></>}
 {entity==='users'&&<label className="check-label"><input type="checkbox" checked={v.active} onChange={e=>update('active',e.target.checked)}/>Usuário ativo</label>}
 <div className="form-actions"><button type="button" className="button secondary" onClick={onClose} disabled={busy||geo}>Cancelar</button><button className="button" disabled={busy||geo}>{busy?'Salvando…':'Salvar cadastro'}</button></div></form>
}
export function ClientDetail({id,ctx,onClose}:{id:number;ctx:Ctx;onClose:()=>void}){
 const {data:c,loading,error,reload}=useApi('/clients/'+id),[editing,setEditing]=useState(false),[geo,setGeo]=useState(false),[geoError,setGeoError]=useState('');
 return <Modal wide title="Ficha do cliente" onClose={onClose}>{loading?<Loading/>:error?<ErrorBox message={error}/>:editing?<RegistryForm entity="clients" initial={c} ctx={ctx} onClose={()=>setEditing(false)} onSaved={()=>{setEditing(false);reload();ctx.notify('Cadastro atualizado.')}}/>:<><div className="client-profile"><Avatar name={c.name} src={c.photo_url}/><div><h2>{c.name}</h2><p>CPF {cpf(c.cpf)} · Cadastro #{String(c.id).padStart(4,'0')}</p></div><div className="actions"><button className="button secondary" onClick={()=>setEditing(true)}><Pencil size={16}/>Editar</button><button className="icon-button" onClick={()=>window.print()} aria-label="Imprimir ficha"><Printer size={19}/></button></div></div><div className="detail-grid">{clientFields.filter(([k])=>!['name','cpf','leader_id'].includes(k)).map(([k,label])=><div key={k}><small>{label}</small><strong>{k==='birth_date'?dateBR(c[k]):c[k]??'Não informado'}</strong></div>)}<div><small>Liderança</small><strong>{c.leader?.name||'Sem vínculo'}</strong></div></div><div className="geo-action"><MapPin size={18}/><span>{hasLocation(c)?'Endereço localizado no mapa':'Endereço ainda não localizado no mapa'}</span><button className="text-button" disabled={geo} onClick={async()=>{setGeo(true);setGeoError('');try{await api('/clients/'+id+'/geocode','POST',{});reload();ctx.notify('Endereço localizado. Confira o ponto no mapa.')}catch(e){setGeoError((e as Error).message)}finally{setGeo(false)}}}>{geo?'Localizando…':'Localizar endereço'}</button></div><ErrorBox message={geoError}/><h3 className="subheading"><FileText size={18}/>Histórico de consultas</h3>{!c.appointments.length?<Empty title="Nenhuma consulta registrada"/>:<div className="table-scroll"><table><thead><tr><th>Data</th><th>Especialidade / médico</th><th>Situação</th></tr></thead><tbody>{c.appointments.map((a:Row)=><tr key={a.id}><td>{dateBR(a.slot.date)}</td><td><strong>{a.slot.specialty.name}</strong><small>{a.slot.doctor.name}</small></td><td><Status value={a.status}/></td></tr>)}</tbody></table></div>}</>}</Modal>
}
export default function Registry({entity,ctx}:{entity:string;ctx:Ctx}){
 const[search,setSearch]=useState(''),[delayed,setDelayed]=useState(''),[page,setPage]=useState(1),[form,setForm]=useState<Row|null>(null),[detail,setDetail]=useState<number|null>(null),[remove,setRemove]=useState<Row|null>(null);
 useEffect(()=>{const t=setTimeout(()=>{setDelayed(search);setPage(1)},250);return()=>clearTimeout(t)},[search]);
 const {data,loading,error,reload}=useApi('/'+entity+'?'+query({search:delayed,page})),config=configs[entity],canEdit=ctx.user.level==='admin'||entity==='clients';
 return <><div className="page-heading"><div><div className="eyebrow">CADASTROS</div><h1>{config.title}</h1><p>{config.desc}</p></div>{canEdit&&<button className="button" onClick={()=>setForm({})}><Plus size={18}/>Novo cadastro</button>}</div><section className="panel"><div className="panel-head"><SearchBox value={search} onChange={setSearch} placeholder={['clients','doctors','users'].includes(entity)?'Buscar por nome ou CPF…':'Buscar por nome…'}/><span className="muted">{data?.total||0} cadastrados</span></div><ErrorBox message={error}/>{loading?<Loading/>:!data?.data.length?<Empty/>:<div className="table-scroll"><table><thead><tr><th>{entity==='clients'?'Cliente':'Nome'}</th>{entity==='clients'?<><th>CPF</th><th>Telefone</th><th>Bairro</th></>:entity==='doctors'?<><th>CRM</th><th>Especialidades</th><th>Telefone</th></>:entity==='leaders'?<><th>Bairro</th><th>Telefone</th><th>Clientes</th></>:entity==='users'?<><th>CPF</th><th>Nível</th><th>Status</th></>:null}<th className="right">Ações</th></tr></thead><tbody>{data.data.map((r:Row)=><tr key={r.id}><td><div className="person"><Avatar name={r.name} src={r.photo_url}/><strong>{r.name}</strong></div></td>{entity==='clients'?<><td className="nowrap">{cpf(r.cpf)}</td><td className="nowrap">{phone(r.phone)}</td><td>{r.neighborhood||'—'}</td></>:entity==='doctors'?<><td>{r.crm}</td><td>{r.specialties?.map((s:Row)=>s.name).join(', ')}</td><td>{phone(r.phone)}</td></>:entity==='leaders'?<><td>{r.neighborhood}</td><td>{phone(r.phone)}</td><td>{r.clients_count}</td></>:entity==='users'?<><td>{cpf(r.cpf)}</td><td>{{admin:'Administrador',recepcao:'Recepção',gestor:'Gestor'}[r.level as string]}</td><td><span className={'badge '+(r.active?'completed':'cancelled')}>{r.active?'Ativo':'Inativo'}</span></td></>:null}<td><div className="actions right">{entity==='clients'&&<button className="text-button" onClick={()=>setDetail(r.id)}>Ficha<ArrowRight size={16}/></button>}{canEdit&&<button className="icon-button" onClick={()=>setForm(r)} aria-label={'Editar '+r.name}><Pencil size={16}/></button>}{ctx.user.level==='admin'&&<button className="icon-button danger-text" onClick={()=>setRemove(r)} aria-label={'Excluir '+r.name}><Trash2 size={16}/></button>}</div></td></tr>)}</tbody></table></div>}<Pager data={data} onPage={setPage}/></section>{form&&<Modal wide title={(form.id?'Editar ':'Cadastrar ')+config.single} onClose={()=>setForm(null)}><RegistryForm entity={entity} initial={form} ctx={ctx} onClose={()=>setForm(null)} onSaved={()=>{setForm(null);reload();ctx.notify('Cadastro salvo com sucesso.')}}/></Modal>}{detail&&<ClientDetail id={detail} ctx={ctx} onClose={()=>{setDetail(null);reload()}}/>}{remove&&<Confirm title="Excluir cadastro" text={`Excluir ${remove.name}? Registros com vínculos serão preservados e a exclusão será impedida.`} label="Excluir" danger onClose={()=>setRemove(null)} onConfirm={async()=>{await api('/'+entity+'/'+remove.id,'DELETE');reload();ctx.refresh();ctx.notify('Cadastro excluído.')}}/>}</>
}
