import {useState,type FormEvent} from 'react';
import {Plus,Pencil,Trash2,Ban,CalendarPlus,Check} from 'lucide-react';
import {type Ctx,type Row,api,useApi,query,today,monthNow,dateBR,Status,Modal,Confirm,ErrorBox,Loading,Empty,Field,Calendar} from './lib';
export default function Slots({ctx}:{ctx:Ctx}){
 const[month,setMonth]=useState(monthNow()),[doctor,setDoctor]=useState(''),[specialty,setSpecialty]=useState(''),[create,setCreate]=useState(false),[edit,setEdit]=useState<Row|null>(null),[cancel,setCancel]=useState<Row|null>(null),[remove,setRemove]=useState<Row|null>(null),[moves,setMoves]=useState<Row|null>(null);
 const{data,loading,error,reload}=useApi('/slots?'+query({month,...(doctor?{doctor_id:doctor}:{}),...(specialty?{specialty_id:specialty}:{})}));
 const manage=ctx.user.level==='admin';
 return <><div className="page-heading"><div><div className="eyebrow">GESTÃO DA AGENDA</div><h1>Vagas de atendimento</h1><p>Organize a disponibilidade dos médicos e amplie o acesso ao cuidado.</p></div>{manage&&<button className="button" onClick={()=>setCreate(true)}><Plus size={18}/>Oferecer vagas</button>}</div><div className="mini-stats"><div><CalendarPlus/><span>Vagas oferecidas<strong>{(data||[]).filter((s:Row)=>s.status==='available').reduce((a:number,s:Row)=>a+s.capacity,0)}</strong></span></div><div><Check/><span>Agendamentos<strong>{(data||[]).reduce((a:number,s:Row)=>a+s.booked,0)}</strong></span></div><div><CalendarPlus/><span>Dias de atendimento<strong>{new Set((data||[]).filter((s:Row)=>s.status==='available').map((s:Row)=>s.date)).size}</strong></span></div></div><section className="panel"><div className="panel-head wrap"><input aria-label="Mês das vagas" type="month" value={month} onChange={e=>{if(e.target.value)setMonth(e.target.value)}}/><select aria-label="Médico" value={doctor} onChange={e=>setDoctor(e.target.value)}><option value="">Todos os médicos</option>{ctx.options.doctors?.map((d:Row)=><option key={d.id} value={d.id}>{d.name}</option>)}</select><select aria-label="Especialidade" value={specialty} onChange={e=>setSpecialty(e.target.value)}><option value="">Todas as especialidades</option>{ctx.options.specialties?.map((d:Row)=><option key={d.id} value={d.id}>{d.name}</option>)}</select></div><ErrorBox message={error}/>{loading?<Loading/>:!data?.length?<Empty title="Nenhuma vaga oferecida neste período" text="Use Oferecer vagas para montar a agenda do mês."/>:<div className="table-scroll"><table><thead><tr><th>Data</th><th>Médico / especialidade</th><th>Ocupação</th><th>Situação</th>{manage&&<th>Ações</th>}</tr></thead><tbody>{data.map((s:Row)=><tr key={s.id}><td className="nowrap"><strong>{dateBR(s.date)}</strong><small>{new Date(s.date+'T12:00:00').toLocaleDateString('pt-BR',{weekday:'long'})}</small></td><td><strong>{s.doctor.name}</strong><small>{s.specialty.name}</small></td><td><strong>{s.booked} / {s.capacity}</strong><div className="progress-track table-progress"><i style={{width:Math.min(100,s.booked/s.capacity*100)+'%'}}/></div></td><td><Status value={s.status==='cancelled'?'cancelled':s.booked>=s.capacity?'Lotado':'available'}/></td>{manage&&<td><div className="actions"><button className="icon-button" disabled={s.date<today()} onClick={()=>setEdit(s)} aria-label="Editar capacidade"><Pencil size={16}/></button><button className="icon-button" disabled={s.status==='cancelled'||s.date<today()} onClick={()=>setCancel(s)} aria-label="Cancelar dia e realocar consultas"><Ban size={16}/></button><button className="icon-button danger-text" onClick={()=>setRemove(s)} aria-label="Excluir dia sem histórico"><Trash2 size={16}/></button></div></td>}</tr>)}</tbody></table></div>}</section>
 {create&&<Modal wide title="Oferecer vagas" onClose={()=>setCreate(false)}><SlotForm ctx={ctx} month={month} onClose={()=>setCreate(false)} onSaved={r=>{setCreate(false);reload();ctx.notify(`${r.created} agendas criadas. ${r.existing} já existiam.${r.skipped.length?' Datas inexistentes ignoradas: '+r.skipped.join(', '):''}`)}}/></Modal>}
 {edit&&<Modal title="Editar vagas do dia" onClose={()=>setEdit(null)}><EditSlot slot={edit} onClose={()=>setEdit(null)} onSaved={()=>{setEdit(null);reload();ctx.notify('Vagas atualizadas.')}}/></Modal>}
 {cancel&&<Confirm title="Cancelar dia e realocar consultas" text={`Tornar ${dateBR(cancel.date)} indisponível para ${cancel.doctor.name} / ${cancel.specialty.name}? Os agendamentos serão transferidos para as próximas vagas do mesmo médico e especialidade. Se não houver capacidade, nada será alterado.`} label="Cancelar e realocar" danger onClose={()=>setCancel(null)} onConfirm={async()=>{const r=await api('/slots/'+cancel.id+'/cancel','POST',{});reload();setMoves(r);ctx.notify('Dia cancelado. '+r.count+' consultas realocadas.')}}/>}
 {remove&&<Confirm title="Excluir oferta de vagas" text={`Excluir ${dateBR(remove.date)}? A exclusão só será possível se não houver histórico de consultas.`} label="Excluir" danger onClose={()=>setRemove(null)} onConfirm={async()=>{await api('/slots/'+remove.id,'DELETE');reload();ctx.notify('Oferta excluída.')}}/>}
 {moves&&<Modal title="Resultado da realocação" onClose={()=>setMoves(null)}><p>{moves.count} consultas transferidas. Entre em contato com os clientes para comunicar as novas datas.</p>{moves.moved.map((m:Row)=><div className="today-row" key={m.appointment_id}><strong>Consulta #{m.appointment_id} · Cliente #{m.client_id}</strong><span>{dateBR(m.date)}</span></div>)}</Modal>}
 </>
}
function EditSlot({slot,onClose,onSaved}:{slot:Row;onClose:()=>void;onSaved:()=>void}){const[capacity,setCapacity]=useState(slot.capacity),[error,setError]=useState(''),[busy,setBusy]=useState(false);return <form onSubmit={async e=>{e.preventDefault();setBusy(true);try{await api('/slots/'+slot.id,'PUT',{capacity,status:'available'});onSaved()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}}><p>{dateBR(slot.date)} · {slot.doctor.name}</p><ErrorBox message={error}/><Field label="Quantidade total de vagas"><input type="number" value={capacity} min={Math.max(1,slot.booked)} max={1000} required onChange={e=>setCapacity(Number(e.target.value))}/></Field>{slot.status==='cancelled'&&<p>Salvar reabrirá esta oferta de vagas.</p>}<div className="form-actions"><button type="button" className="button secondary" onClick={onClose}>Voltar</button><button className="button" disabled={busy}>Salvar vagas</button></div></form>}
function SlotForm({ctx,month:initial,onClose,onSaved}:{ctx:Ctx;month:string;onClose:()=>void;onSaved:(r:Row)=>void}){
 const[month,setMonth]=useState(initial),[doctor,setDoctor]=useState(''),[specialty,setSpecialty]=useState(''),[dates,setDates]=useState<string[]>([]),[capacity,setCapacity]=useState(10),[repeat,setRepeat]=useState<string[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const specialties=ctx.options.doctors?.find((d:Row)=>String(d.id)===doctor)?.specialties||[];
 const months=Array.from({length:12},(_,i)=>{const d=new Date(Number(month.slice(0,4)),Number(month.slice(5))+i,1);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`});
 async function submit(e:FormEvent){e.preventDefault();setBusy(true);setError('');try{const result=await api('/slots','POST',{doctor_id:Number(doctor),specialty_id:Number(specialty),capacity,dates,repeat_months:repeat});onSaved(result)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <form onSubmit={submit}><ErrorBox message={error}/><div className="form-grid"><Field label="Médico *"><select value={doctor} onChange={e=>{setDoctor(e.target.value);setSpecialty('')}} required><option value="">Selecione o médico</option>{ctx.options.doctors?.map((d:Row)=><option key={d.id} value={d.id}>{d.name}</option>)}</select></Field><Field label="Especialidade *"><select value={specialty} onChange={e=>setSpecialty(e.target.value)} required><option value="">Selecione</option>{specialties.map((s:Row)=><option key={s.id} value={s.id}>{s.name}</option>)}</select></Field></div><div className="slot-form-grid"><Calendar multi month={month} onMonth={s=>{setMonth(s);setDates([]);setRepeat([])}} selected={dates} onSelect={d=>setDates(old=>old.includes(d)?old.filter(s=>s!==d):[...old,d])}/><div><Field label="Quantidade de vagas por dia *"><input type="number" min={1} max={1000} value={capacity} required onChange={e=>setCapacity(Number(e.target.value))}/></Field><div className="notice">{dates.length} dias selecionados · {dates.length*capacity} vagas no mês</div><h3>Repetir nos meses</h3><p className="muted">Repete os mesmos números de dia. Datas inexistentes, como 31 de fevereiro, serão ignoradas.</p><div className="repeat-months">{months.map(m=><label key={m}><input type="checkbox" checked={repeat.includes(m)} onChange={e=>setRepeat(old=>e.target.checked?[...old,m]:old.filter(s=>s!==m))}/>{new Date(m+'-01T12:00:00').toLocaleDateString('pt-BR',{month:'short',year:'numeric'})}</label>)}</div></div></div><div className="form-actions"><button type="button" className="button secondary" onClick={onClose}>Cancelar</button><button className="button" disabled={busy||!dates.length}>{busy?'Criando…':'Publicar vagas'}</button></div></form>
}
